version: 2
jobs:
  test:
    working_directory: /go/src/github.com/kynrai/dynamodbx
    docker:
      - image: circleci/golang:latest
      - image: amazon/dynamodb-local:latest
    steps:
      - checkout
      - run: make
workflows:
  version: 2
  build_and_test:
    jobs:
      - test
